<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;

class Lead extends Model
{
    use SoftDeletes;
    protected $dates = ['deleted_at'];

    public function save(array $options = [])
    {
        parent::save();
        $created_at = Carbon::parse($this->created_at)->diffInSeconds();

        if($created_at > 7){
            $role = Auth::user()->Role->id;
            if($role == 1){
                $this->update_admin = Carbon::now()->toDateTimeString();
            }elseif($role == 2){
                $this->update_caller = Carbon::now()->toDateTimeString();
            }
        }
         return parent::save($options); // TODO: Change the autogenerated stub
    }

    public function Product(){
        return $this->belongsTo('App\Models\Product');
    }

    public function Supplier(){
        return $this->belongsTo('App\Models\Supplier');
    }

    public function AdminStatus(){
        return $this->belongsTo('App\Models\Status','status_admin','id');
    }

    public function CallerStatus(){
        return $this->belongsTo('App\Models\Status','status_caller','id');
    }
}
